#问题模型
QUESTION_MODEL_PICO = 'PICO'
QUESTION_MODEL_PICOT = 'PICOT'
QUESTION_MODEL_PECO = 'PECO'
QUESTION_MODEL_PEO = 'PEO'
QUESTION_MODEL_CoCoPop = 'CoCoPop'
QUESTION_MODEL_PIRD = 'PIRD'
QUESTION_MODEL_SPIDER = 'SPIDER'
QUESTION_MODEL_SPICE = 'SPICE'
QUESTION_MODEL_ECLIPSe = 'ECLIPSe'

#问题类型
QUESTION_TYPE_INTEVENTION_TIME = 'Interventional Question with Time Dimension'
QUESTION_TYPE_INTEVENTION = 'Interventional Question without Time Dimension'
QUESTION_TYPE_OBSERVATION_TIME = 'Observational Question with Comparison'
QUESTION_TYPE_OBSERVATION = 'Observational Question without Comparison'
QUESTION_TYPE_PREVALENCE = 'Prevalence / Incidence Question'
QUESTION_TYPE_DIAGNOSIS = 'Diagnostic Test Accuracy Question'
QUESTION_TYPE_QUALITATION = 'Qualitative Question'
QUESTION_TYPE_HEALTH_PRACTICE = 'Health Practice Question'
QUESTION_TYPE_HEALTH_SERVICE = 'Health Service Question'

#研究设计类型
RESEARCH_TYPE_COHORT = 'Cohort Study'
RESEARCH_TYPE_CASE_CONTROL = 'Case-Control Study'
RESEARCH_TYPE_CROSS_SECTIONAL = 'Cross-Sectional Study'
RESEARCH_TYPE_RCT = 'Randomized Controlled Trial'
RESEARCH_TYPE_NRCT = 'Non Randomized Controlled Trial'
RESEARCH_TYPE_SAT = 'Single Arm Trial'
RESEARCH_TYPE_TAT = 'Three Arm Trial'
RESEARCH_TYPE_CROSS = 'Crossover Trial'
RESEARCH_TYPE_FACTORIAL = 'Factorial Trial'
RESEARCH_TYPE_FGD = 'Focus Group Discussion'
RESEARCH_TYPE_IN_DEPTH = 'In-depth Interview'
RESEARCH_TYPE_BEFORE_AFTER = 'Before-and-After Study'
RESEARCH_TYPE_ECOLOGICAL = 'Ecological Study'